### ISSUE TITLE
Modal content is not scrollable

### ISSUE THREAD

**Issue by alkihis** [holtzy/data_to_viz#33]
In the main page, when clicking on a chart type, modal content is not scrollable (due to `pointer-events: none`), so text is truncated.

```css
.modal-dialog {
    pointer-events: all;
}
```

or 

```css
.portfolio-modal .modal-dialog {
    max-height: unset;
}
```
